{% set name = "flake8-type-checking" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-type-checking-{{ version }}.tar.gz
  sha256: 02a6fb042600d7acfac59602ee1ff41685c1b79f386394688c93c0dd36d7bf9a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - flake8
    - python >=3.6

test:
  imports:
    - flake8_type_checking
  commands:
    - pip check
    - flake8 --version | grep flake8-type-checking
  requires:
    - flake8
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/snok
  summary: A flake8 plugin for managing type-checking imports & forward references
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
