{% set name = "flake8-type-checking" %}
{% set version = "2.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-type-checking-{{ version }}.tar.gz
  sha256: a47b790ae6e13cb4c62ea36a3197eaa7b635086544071e3a49d6751f0b6cabe6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6
  run:
    - aspy.refactor-imports
    - classify-imports
    - flake8
    - python >=3.6

test:
  imports:
    - flake8_type_checking
  commands:
    - pip check
    - flake8 --version | grep flake8-type-checking
  requires:
    - flake8
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/snok/flake8-type-checking
  summary: A flake8 plugin for managing type-checking imports & forward references
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
