{% set name = "flake8-type-checking" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: acd5c08cc618e9b3a6257246e5cdf5c0d5b2ba2c5120e20df880823fe84de738

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - aspy.refactor-imports
    - classify-imports
    - flake8
    - python >={{ python_min }}

test:
  imports:
    - flake8_type_checking
  commands:
    - pip check
    - flake8 --version | grep flake8-type-checking
  requires:
    - flake8
    - m2-grep  # [win]
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/snok/flake8-type-checking
  summary: A flake8 plugin for managing type-checking imports & forward references
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
